@startuml stem

class Stem extends Entity implements OnTurn{
    maxSporeThrows : Integer
    numThrownSpores : Integer
    spores : List<Spore>
    level : Integer
    throwSpore(s : Spore, t : Tecton) : Boolean
    getColony() : Colony
}

@enduml