@startuml MushroomerThrowsClawParalyzingSporeFromStemToTecton
title Mushroomer throws claw paralyzing spore from stem to tecton

actor Controller
participant "mr : Mushroomer" as MR
participant "ms : MushroomStem" as MS
participant "t : Tecton" as T
participant "sp : Claw paralyzing Spore" as SP

activate Controller
Controller -> MR : add(t, sp)
activate MR

MR -> MS : add(t, sp)
activate MS

MS -> T : add(sp)
activate T

MS <-- T : true
deactivate T

MS -> MS : remove(sp)
MR <-- MS : true
deactivate MS

deactivate MR
@enduml