@startuml insect

Insect *-- "0..*" Effect
class Insect extends Entity implements IInsect{
    effects : List<Effect>
    paralized : Boolean
    clawParalized : Boolean
    baseSpeed : Integer
    speedModifier : Integer
}

@enduml