@startuml insectCutThread

title Insect cuts thread

actor Controller
participant "ir : Insecter" as IR
participant  "i : Insect" as I
participant "mt : MushroomThread" as M
participant "t : Tecton" as T

activate Controller
Controller -> IR: cut(mt)

activate IR
IR -> I: cut(mt)
activate I

alt clawParalized
    IR <-- I : false

else
    I -> M: gotCut()
    activate M
    
    I <-- M
    deactivate M

    IR <-- I : true
end
deactivate I

@enduml