@startuml growThread
title Mushroomer grows thread on a tecton

actor Controller
participant "mr : Mushroomer" as MR
participant "t : Tecton" as T

activate Controller
Controller -> MR : add(t, th)
activate MR

MR -> T : add(th)
activate T

MR <-- T : true
deactivate T

deactivate MR
@enduml