@startuml growThreadOnSingle
title Mushroomer grows thread on an occupied single threaded tecton

actor Controller
participant "mr : Mushroomer" as MR
participant "t : Signle threaded tecton" as T

activate Controller
Controller -> MR : add(t, th)
activate MR

MR -> T : add(th)
activate T

MR <-- T : false
deactivate T

deactivate MR
@enduml