@startuml growThreadOnSingle
title Mushroomer grows thread on a single threaded tecton

actor Controller
participant "mr : Mushroomer" as MR
participant "t : Tecton" as T

activate Controller
Controller -> MR : add(t, th)
activate MR

MR -> T : add(t, th)
activate T

alt empty

MR <-- T : true

else
MR <-- T : false
deactivate T
end

deactivate MR
@enduml