@startuml Mushroomer ends turn

title Mushroomer ends turn

actor Controller
participant "mr : Mushroomer" as MR
participant "s : Mushroomstem" as S
participant "th : Mushroomthread" as TH
participant "t : Tecton" as T
participant "newS : Mushroomstem" as NS

activate Controller
Controller -> MR : endTurn()
activate MR

loop for(s : stems)
    MR -> S : endTurn()
    activate S

    MR <-- S
    deactivate S
end

loop for(th : threads)
    MR -> TH : endTurn()
    activate TH

    TH -> TH : getLocation()
    TH -> NS **: new
    TH -> T: add(newS)
    activate T

    TH <-- T : success
    deactivate

    alt success
        MR <-- TH : add(newS)
        activate MR
        MR -> TH
        deactivate MR
    end
    MR <-- TH
    deactivate TH
end


@enduml