@startuml Mushroomer starts turn

title Mushroomer starts turn

actor Controller
participant "mr : Mushroomer" as MR
participant "s : Stem" as S
participant "th : Thread" as TH
participant "t : Tecton" as T

activate Controller
Controller -> MR : onTurn()
activate MR

loop for(s : stems)
    MR -> S : onTurn()
    activate S

    MR <-- S
    deactivate S
end

loop for(th : threads)
    MR -> TH : onTurn()
    activate TH

    TH -> T : getLocation()
    activate T
    alt  not hasStem() and getSporeCount() > 5


    TH <-- T
    end

    MR <-- TH
    deactivate TH
end


@enduml