@startuml Mushroomer starts turn

title Mushroomer starts turn

actor Controller
participant "mr : Mushroomer" as MR
participant "th : Thread" as TH
participant "s : Stem" as S

activate Controller
Controller -> MR : onRound()
activate MR

MR -> MR : onRound()
loop for(th : threads)
    MR -> TH
    activate TH
    TH -> TH : onRound()

    MR <-- TH
    deactivate TH
end

loop for(s : stems)
    MR -> S
    activate S
    S -> S : onRound()

    MR <-- S
    deactivate S
end

@enduml