@startuml Round ends for threadconsuming tecton
title  Round ends for threadconsuming tecton

actor Controller
participant "t : Threadconsuming tecton" as T
participant "mt : Mushroomthread" as MT

activate Controller
Controller -> T : onRound()
activate T

loop for(mt : mushroomthreads)
    
end

deactivate T

@enduml