@startuml spore

abstract class Effect {
    {abstract} duration : Integer
    {abstract} effect(i : Insect) : void
}

class Fast extends Effect {}
class Slow extends Effect {}
class Paralyze extends Effect {}
class ClawParalyze extends Effect {}

@enduml