@startuml fungorium
!include core/core.puml
!include insect/effect.puml
!include insect/insect.puml
!include mushroom/mushroom.puml
!include mushroom/spore.puml
!include mushroom/stem.puml
!include mushroom/thread.puml
!include map/map.puml
!include map/tecton.puml
!include player/player.puml
!include player/mushroomer.puml
!include player/insecter.puml