@startuml interface

interface OnTurn{
    {abstract} onTurn() : void
}

interface OnRound{
    {abstract} onRound() : void
}

interface IInsect implements OnTurn{
    {abstract} eat(s : Spore) : Boolean
    {abstract} move(t : Tecton) : Boolean
    {abstract} cut(t : Thread) : Boolean
}

interface IMushroom{
    {abstract} add(t : Tecton, s : Spore) : Boolean
    {abstract} add(t : Tecton, s : Stem) : Boolean
    {abstract} add(t : Tecton, t : Thread) : Boolean
    {abstract} remove(t : Tecton, s : Spore) : Boolean
    {abstract} remove(t : Tecton, s : Stem) : Boolean
    {abstract} remove(t : Tecton, t : Thread) : Boolean
}

@enduml