@startuml tecton

interface IMushroom{
    {abstract} addStem(t : Tecton, s : Stem) : Boolean
    {abstract} addThread(t : Tecton, t : Thread) : Boolean
    {abstract} addSpore(t : Tecton, s : Spore) : Boolean
}

Tecton *-- "0..1" Stem
Tecton *-- "0..*" Spore
Tecton *-- "0..*" Thread
Tecton *-- "0..*" Insect
class Tecton implements OnRound, IMushroom{
    neighbours : List<Tecton>
    stem : Stem
    threads : List<Thread>
    spores : List<Spore>
    insects : List<Insect>
    addInsect(i : Insect) : void
}

class StemlessTecton extends Tecton {}
class ThreadConsumingTecton extends Tecton {}
class SingleThreadedTecton extends Tecton {}
@enduml