@startuml mushroom

interface IMushroom{
    {abstract} add(t : Tecton, sp : Spore) : Boolean
    {abstract} add(t : Tecton, st : Stem) : Boolean
    {abstract} add(t : Tecton, th : Thread) : Boolean
    {abstract} remove(t : Tecton, sp : Spore) : Boolean
    {abstract} remove(t : Tecton, st : Stem) : Boolean
    {abstract} remove(t : Tecton, th : Thread) : Boolean
}

Mushroom *-- "1..*" Stem
Mushroom *-- "1..*" Thread
Mushroom *-- "0..*" Spore
class Mushroom implements IMushroom, OnTurn{
    thrownSpores : List<Spore>
    stems : List<Stem>
    thread : List<Thread>
}

@enduml