@startuml levelUp
title Mushroomstem levels up

actor Controller
participant "M:MushroomStem" as M

group max. once per turn
Controller -> M: increase level variable
activate M

M --> Controller
deactivate M
end


@enduml