@startuml startTurn_mushroomer
title Mushroomer's turn starts

actor Controller
participant "P:Mushroomer" as P
participant "M:MushroomStem" as M
participant "C:Colony" as C
'participant ""

Controller -> P : onTurn()
activate P

    loop for(t in stems)
        P -> M : onTurn()
        activate M
        P <-- M
        deactivate M 
    end

    loop for(c in colonies)
        alt c has no stems
            P -> C : Destroy()
        end
    end

Controller <-- P
deactivate P

@enduml