
@startuml
title Eat with insect
skinparam linestyle ortho
actor Insecter as 0
rectangle "map: Map" as 1
rectangle "tecton: Tecton" as 2.1
rectangle "insect: Insect" as 3
rectangle "spore: Spore" as 4

0 -- 3 :  1. → eat(spore)
3 -- 2.1:  2. → eat(spore)
2.1 -- 1
2.1 -- 4

@enduml
