@startuml effect

abstract class Effect{
    {static} duration : Integer
    durationRemaining : Integer

    {static} doesStun : Boolean
    {static} speedModifier : Integer

    doesStun() : Boolean
    getSpeedModifier() : Integer
}

Slow --|> Effect
class Slow {
    doesStun() : Boolean
    getSpeedModifier() : Integer
}

Fast --|> Effect
class Fast {
    doesStun() : Boolean
    getSpeedModifier() : Integer
}

Paralyze --|> Effect
class Paralyze {
    doesStun() : Boolean
    getSpeedModifier() : Integer
}

ClawParalyze --|> Effect
class ClawParalyze {
    doesStun() : Boolean
    getSpeedModifier() : Integer
}


@enduml