@startuml destroyColony
title Destroy Colony function

' EZ CSAK A DESTROY COLONY FV MŰKÖDÉSE, ezért nem a Controller az actor

actor Mushroomer as A

participant "C:Colony" as C
participant "M:MushroomStem" as M
participant "M:MushroomThread" as T

A -> C : Destroy()

activate C
loop for m in C.MushroomStems
    C -> M : removeFromGame()
    activate M
    C <-- M
    deactivate M
end

loop for t in C.MushroomThreads
    C -> T : removeFromGame()
    activate T
    C <-- T
    deactivate T
end
A <-- C

@enduml