@startuml endRound
title Round ends

actor Controller
participant "m:Map" as M
participant "t:Tecton" as T
participant "mt:MushroomThread" as MT

Controller -> M: endRound()

activate M
loop for(t : tectons)
    M -> T: endRound()
    activate T
    M <-- T
    deactivate T

    alt random

        M -> T: splitTecton(t)

        activate T
        loop for(mt : t.getMushroomThreads())
            T -> MT: removeEntity(mt)
            activate MT

            T <-- MT
            deactivate MT
        end
    end
end
M <-- T
deactivate T

Controller <-- M
deactivate M
@enduml