@startuml moveInsect
title Insecter makes insect eat a spore

actor Controller
participant "ir : Insecter" as IR
participant "i : Insect" as I
participant "s:Spore" as T1
participant "e:Effect" as E
participant "T:Tecton" as T

Controller -> IR: moveInsect(Tecton)
activate IR
IR -> I: move(T2) 
activate I

    loop for(e in effects)
        I -> E : doesStun()
        I <-- E : doesStun
    end
    alt does any effect stun = false


I -> T1: getEffect()
activate T1
T1 --> I: Effect e2
deactivate T1

I -> I : add e2 to effects

I -> T: removeSpore(Spore)
activate T
T --> I:
deactivate T
end
I --> IR

deactivate I

Controller <-- IR
deactivate IR
deactivate IR
@enduml