@startuml insectCutThread

title Insect cuts thread


actor "ir : Insecter" as IR
participant  "i : Insect" as I
participant "mt : MushroomThread" as M

activate IR
IR -> I: cutThread(mt) : void
I -> M: cut(M) : void
activate M
M--> I

deactivate M
I-->IR

deactivate I

@enduml