@startuml moveInsect
title Insecter moves Insect

actor Controller
participant "ir : Insecter" as IR
participant "i : Insect" as I
participant "t1:Tecton" as T1
participant "t2:Tecton" as T2

Controller -> IR: moveInsect()
activate IR
IR -> I: move(T2) 
activate I
I -> T1: removeInsect(I)
activate T1
T1 --> I:
deactivate T1
I -> T2: addInsect(I)
activate T2
T2 --> I:
deactivate T2

I --> IR

deactivate I

deactivate IR
deactivate IR
@enduml