@startuml levelUp
title Mushroomstem levels up

actor Controller
participant "P:Mushroomer" as P
participant "M:MushroomStem" as M

Controller-->P
activate P
P -> M: LevelUp(M) : void
activate M
M --> P
deactivate M

P --> Controller 
deactivate P

@enduml