@startuml startGame
title Player starts game

actor Controller
participant "M:Map" as M
participant "T:Tecton 1" as T

Controller -> M : generate()

activate M
    loop
        M --> T : new Tecton()
        M <-- T

        loop
            activate T
                M -> T : addNeighbor(Tecton)
                M <-- T
            deactivate T
        end
    end
Controller <-- M
@enduml