@startuml throwSpore

title Mushroomer throws Spore


actor "P:Mushroomer" as P
participant "M:MushroomStem" as M
participant "T:Tecton" as T

P -> M: throwSpore(M,T) : void
activate M
M ->> M: isEnoughEnergy() : bool
M --> P: False
M --> M: True
activate T
M -> T : addSpores(Spore) : integer
T --> M
deactivate T
M --> P
deactivate M

@enduml