@startuml throwSpore

title Mushroomer throws Spore

actor Controller
participant "P:Mushroomer" as P
participant "M:MushroomStem" as M
participant "T:Tecton" as T

Controller -> P : throwSpore(M, T, S)
activate P

P -> M: throwSpore(T, S) : void
activate M
alt Player has enough energy

M -> T : addSpore(Spore)
activate T
T --> M
deactivate T
end
M --> P
deactivate M

Controller <-- P
deactivate P

@enduml