@startuml effect

abstract class Effect{
    {static} duration : Integer
    durationRemaining : Integer
}

Slow --|> Effect
class Slow {
}

Fast --|> Effect
class Fast {
}

Paralyze --|> Effect
class Paralyze {
}

ClawParalyze --|> Effect
class ClawParalyze {
}


@enduml