@startuml effect

abstract class Effect{
    {static} duration : Integer
    DurationRemainging : Integer
}

Slow --|> Effect
class Slow {
}

Fast --|> Effect
class Fast {
}

Paralize --|> Effect
class Paralize {
}

ClawParalize --|> Effect
class ClawParalize {
}


@enduml