@startuml entity
abstract class Entity {
    owner : Player
}

interface IEffect{
    effect(Insect) : void
}

interface IOnTurn{
    onTurnEnd() : void
}

interface IOnRound{
    onRoundEnd() : void
}
@enduml