@startuml fungorium
package fungorium{
    !include player.puml
    !include map.puml
    !include tecton.puml
    !include entity.puml
    !include spore.puml
    !include mushroomThread.puml
    !include mushroomStem.puml
    !include insect.puml
    !include colony.puml
    !include effect.puml
}
@enduml