@startuml insect

Entity <|-- Insect
Insect *-- Effect

IOnTurn <|.. Insect
class Insect{
    effects : List<Effect>
    eat(Spore) : boolean
    move(Tecton) : boolean
    cut(MushroomThread) : boolean
    OnTurn() : void
}
@enduml