@startuml insect

Entity <|-- Insect
Insect *-- Effect

IOnTurn <|.. Insect
class Insect{
    effects : List<Effect>
    eat(Spore) : Boolean
    move(Tecton) : Boolean
    cut(MushroomThread) : Boolean

    isStunned() : Boolean
    getSpeed() : Integer

    onTurn() : void
}
@enduml