@startuml map
IOnTurn <|.. Map 
IOnRound <|.. Map
Map "1" *-- "0..*" Tecton
class Map{
    tectons : Tecton[]
    generate() : void
    splitTecton(Tecton) : void
    getRandomTection() : Tecton
}
@enduml