@startuml mushroomStem

IOnTurn <|.. MushroomStem
IOnRound <|.. MushroomStem
Entity <|-- MushroomStem 
class MushroomStem{
    {static} maxSporeThrows : Integer
    energy: Integer
    level: Integer
    thrownSpores: Integer
    isDead(): boolean
    getColony() : Colony
    throwSpores(Spores, Tecton) : void
}
@enduml