@startuml mushroomStem

MushroomStem <|-- Entity
class MushroomStem{
    level: int
    sporeThrowCnt: int
    getEnergy(): int
    isDead(): boolean
    getColony() : Colony
    throwSpore() : void
}
@enduml