@startuml mushroomStem

IOnTurn <|.. MushroomStem
'IOnRound <|.. MushroomStem
Entity <|-- MushroomStem 
class MushroomStem{
    {static} maxSporeThrows : Integer
    thrownSpores: Integer
    spores : List<Spores>
    level: Integer
    throwSpore(Spore, Tecton) : Boolean
    onTurn(): void
    getColony() : Colony

    deleteFromGame() : void
    ' remove this stem from tecton and from owner player's list
}
@enduml