@startuml player
Player <|.. IOnTurn
Player <|.. IOnRound
abstract class Player{
    id : Integer
}

Player <|-- Mushroomer
Mushroomer o-- "0..*" Spores
Mushroomer o-- "1..*" MushroomStem
Mushroomer o-- "0..*" MushroomThread
class Mushroomer{
    colonies : Colony[]
    plantBody(Tecton) : void
    throwSpore(Tecton, Spores) : void
}

Player <|-- Insecter
Insecter o-- Insect
class Insecter{
    insect : Insect
    moveInsect(Insect) : void
    cutThread(Insect) : void
}
@enduml