@startuml spore

Tecton *-- Spores

abstract class Spores{
    Nutrition : Integer
    abstract effect(Insect) : void
}

SlowingSpore <|--Spores
class SlowDownSpore{
    effect(Insect) : void

}

SpeedingSpore <|--Spores
class SpeedUpSpore{
    effect(Insect) : void

}

InsectParalizingSpore <|--Spores
class InsectParalizingSpore{
    effect(Insect) : void

}

ClawParalizingSpore <|--Spores
class MouthParalizingSpore{
    effect(Insect) : void

}
@enduml	