@startuml spore

Spore <|-- Entity

abstract class Spore{
    Nutrition : Integer
    abstract effect(Insect) : void
}

SlowingSpore <|--Spore
class SlowingSpore{
    effect(Insect) : void

}

SpeedingSpore <|--Spore
class SpeedingSpore{
    effect(Insect) : void

}

ParalizingSpore <|--Spore
class ParalizingSpore{
    effect(Insect) : void

}

ClawParalizingSpore <|--Spore
class ClawParalizingSpore{
    effect(Insect) : void

}
@enduml	