@startuml
Tecton "2..12" -- Tecton : neighbour
Tecton o-- "0..*" Entity
Tecton *-- "0..1" Body
class Tecton {
  neighbours : List<Tecton>
  entities : List<Entity>
  void split()
  void effect()
}

Tecton <|-- SingleThreadedTecton
class SingleThreadedTecton <<SingleThreaded>> {
}

Tecton <|-- BodylessTecton
class BodylessTecton <<Bodyless>>{

}

Tecton <|-- ThreadConsumingTecton
class ThreadConsumingTecton <<ThreadConsuming>>{

}
@enduml