@startuml Communication diagram

rectangle "Controller" as Controller

rectangle "Map" as Map

package "Tectons" {
    rectangle "tecton1: Tecton" as tecton1
    rectangle "tecton2: Tecton" as tecton2
    rectangle "tecton3: StemlessTecton" as tecton3
    rectangle "tecton4: ThreadConsumingTecton" as tecton4
    rectangle "tecton5: SingleThreadedTecton" as tecton5
}

package "Insecters" {
    rectangle "insecter1: Insecter" as insecter1
    rectangle "insecter2: Insecter" as insecter2
}

package "Mushroomers" {
    rectangle "mushroomer1: Mushroomer" as mushroomer1
    rectangle "mushroomer2: Mushroomer" as mushroomer2
}

package "Insects" {
    rectangle "insect1: Insect" as insect1
    rectangle "insect2: Insect" as insect2
}

package "MushroomThreads" {
    rectangle "thread1: MushroomThread" as thread1
    rectangle "thread2: MushroomThread" as thread2
}

package "MushroomStems" {
    rectangle "stem1: MushroomStem" as stem1
    rectangle "stem2: MushroomStem" as stem2
    rectangle "stem3: MushroomStem" as stem3
}

package "Spores" {
    rectangle "speeding: SpeedingSpore" as speeding
    rectangle "slowing: SlowingSpore" as slowing
    rectangle "paralyzing: ParalyzingSpore" as paralyzing
    rectangle "clawParalyzing: ClawParalyzingSpore" as clawParalyzing
}

Controller -up-> Map : 0: <<create>> \n 0.5: generate()

' Creating tectons and assigning neighbors
Map -up---> tecton1 : 1: <<create>>\n6: addNeighbour(tecton2)
Map -up---> tecton2 : 2: <<create>>\n7: addNeighbour(tecton1)\n8: addNeighbour(tecton3)\n10: addNeighbour(tecton4)
'\n36: add(thread1)\n39: add(thread2)\n49: add(slowing)
Map -up---> tecton3 : 3: <<create>>\n9: addNeighbour(tecton2)\n12: addNeighbour(tecton4)
Map -up---> tecton4 : 4: <<create>>\n11: addNeighbour(tecton2)\n13: addNeighbour(tecton3)\n14: addNeighbour(tecton5)
mushroomer2 --down--> tecton4 : 32: add(stem3) \n 40: add(thread2)
mushroomer2 --->> tecton2 : 49: add(slowing)\n 52: add(clawParalyzing)

mushroomer1 -> tecton1 : 26: add(stem1)\n 35: add(thread1)\n 43: add(speeding)\n 46: add(paralyzing)
mushroomer1 -left-> tecton2 : 29: add(stem2)

insecter1 ----> tecton1 : 17: addInsect(insect1)
insecter2 ----> tecton2 : 19: addInsect(insect2)

Map -up---> tecton5 : 5: <<create>>\n15: addNeighbour(tecton4)

' Creating insects and adding them to tectons
insecter1 -up-> insect1 : 16: <<create>>
insecter2 -up-> insect2 : 18: <<create>>

' Creating players
Controller --> insecter1 : 20: <<create>>\n\n
Controller --> insecter2 : 21: <<create>>\n
Controller -up--> mushroomer1 : 22: <<create>>\n25: add(stem1)\n28: add(stem2)\n34: add(thread1)\n42: add(speeding)\n45: add(paralyzing)
Controller -up--> mushroomer2 : 23: <<create>>\n31: add(stem3)\n38: add(thread2)\n48: add(slowing)\n51: add(clawParalyzing)

' Creating stems and adding them
Controller ----> stem1 : 24: <<create>>
Controller ----> stem2 : 27: <<create>>
Controller ----> stem3 : 30: <<create>>

' Creating threads and adding them
Controller ----> thread1 : 33: <<create>>
Controller ----> thread2 : 37: <<create>>

' Creating spores and adding them
Controller ---> speeding : 41: <<create>>
Controller ---> paralyzing : 44: <<create>>
Controller ---> slowing : 47: <<create>>
Controller ---> clawParalyzing : 50: <<create>>

@enduml
