@startuml  Insecter's insect eats claw paralyzing spore
title Insecter's insect eats claw paralyzing spore

actor Controller
participant "ir : Insecter" as IR
participant "i : Insect" as I
participant "s : Claw paralyzing spore" as S
participant "e : Claw paralyze" as E
participant "t : Tecton" as T
participant "mr : Mushroomer" as MR

Controller -> IR: eat(s)
activate IR
IR -> I: eat(s)
activate I

alt paralyzed
    IR <-- I : false
else

    I -> S : remove(i)
    activate S

    S -> E : apply(i)
    activate E

    E -> I : apply(e)

    S <-- E
    deactivate E

    S -> T : getLocation()
    activate T
    T -> T : remove(s)
    S <--T
    deactivate T

    S -> MR : getPlayer()
    activate MR
    MR -> MR : remove(s)
    S <-- MR
    deactivate MR

    I <-- S
    deactivate S
    IR <-- I : true
end
deactivate I

Controller <-- IR
deactivate IR
deactivate IR
@enduml