@startuml Mushroomer throws claw paralyzing spore on tecton
title Mushroomer throws claw paralyzing spore on tecton

actor Controller
participant "mr : Mushroomer" as MR
participant "t : Tecton" as T
participant "sp : Claw paralyzing Spore" as SP

activate Controller
Controller -> MR : add(t, sp)
activate MR

MR -> T : add(t, sp)
activate T

MR <-- T : true
deactivate T

deactivate MR
@enduml