@startuml Insecter ends turn

title Insecter ends turn

actor Controller
participant "ir : Insecter" as IR
participant "i : Insect" as I
participant "e : Effect" as E

activate Controller
Controller -> IR : endTurn()
activate IR

IR -> I : endTurn()
activate I

loop for(e : effects)
    alt duration == 1
        I -> E : remove(i)
        activate E
        I <- E : remove(e)
        I <-- E
        deactivate E
    end
    deactivate E
end

IR <-- I
deactivate I

@enduml