@startuml core

interface ITurn{
    {abstract} endTurn() : void
}

interface IRound{
    {abstract} endTurn() : void
}

abstract class Entity implements IOnTurn{
    {abstract} location : Tecton
    {abstract} owner : Player
}

@enduml