@startuml thread

interface IThread{
    {abstract} add(t : Tecton, th : Thread) : Boolean
    {abstract} remove(t : Tecton, th : Thread) : Boolean
}

class MushroomThread extends Entity{
    getConnected() : List<Thread>
}

@enduml