@startuml stem

interface IStem{
    {abstract} add(ms: Mushroomstem) : Boolean
    {abstract} remove(ms : Mushroomstem) : Boolean
    {abstract} levelUp() : Boolean
}

MushroomStem *-- Spore
class MushroomStem extends Entity implements ISpore{
    maxSporeThrows : Integer
    numThrownSpores : Integer
    throwableSpores : List<Spore>
    level : Integer
}

@enduml