@startuml spore

interface ISpore {
    {abstract} add(sp : Spore) : Boolean
    {abstract} remove(sp : Spore) : Boolean
}

abstract class Spore extends Entity{
    {abstract} nutrition : Integer
    {abstract} effect : Effect
    {abstract} remove(i : Insect) : Boolean
}

class SpeedingSpore extends Spore {}
class SlowingSpore extends Spore {}
class ParalyzingSpore extends Spore {}
class ClawParalyzingSpore extends Spore {}

@enduml