@startuml stem

interface IStem{
    {abstract} add(th : Stem) : Boolean
    {abstract} remove(th : Stem) : Boolean
    {abstract} levelUp() : Boolean
}

Stem *-- Spore
class Stem extends Entity implements ISpore{
    maxSporeThrows : Integer
    numThrownSpores : Integer
    throwableSpores : List<Spore>
    level : Integer
}

@enduml