@startuml splitSpore

' KÉSZ : Dúcz

title SplitSpore
actor Controller
participant "in:Insecter" as In
participant "i1:Insect" as I

participant "s:SplitEffect" as S
participant "i2:Insect" as I2
'participant "t:tecton" as T

activate In
Controller->In: endTurn()
activate I
In-> I: endTurn()
I->S : decreaseDuration()
activate S

S-->I
deactivate S

I->S : apply(Insect i1)
activate S

S->I : split()
activate I

I -> I2 : <<create>>
I -> In : add(Insect i2)
In --> I

I-->S
deactivate I

S-->I
deactivate S

I --> In

deactivate I
In --> Controller
deactivate In



@enduml